def message_map():
    message_values_maps = {
        "User doesn't belong to any group": "The User is not part of any group",
        "Already Enabled": "Enabled Already",
        "This has a recommended value": "This is worth a recommendation",
        "User should contact the admin to reset the expired password": "User should contact admin to reset the password expired",
        "Root user access keys are not active": "Access keys for the root user are not active",
        "User account is not MFA enabled": "MFA is not enabled for this User account",
        "User account is MFA enabled": "MFA is enabled for this User account",
        "VPC flow logs are not enabled.": "VPC flow logs are not enabled",
        "Subnet has route to the world.": "This Subnet has a route to 0.0.0.0",
        "Subnet does not have route to the world.": "This Subnet does not have a route to 0.0.0.0/0",
        "Key pair is not used": "This Key pair is not being used ",
        "MSSQL port is not open to entire world": "MSSQL port is not open to 0.0.0.0/0",
        "MSSQL Port is open to entire world": "MSSQL port is open to 0.0.0.0/0",
        "MySQL port is not open to entire world": "MySQL port is not open to 0.0.0.0/0",
        "MySQL Port is open to entire world": "MySQL port is open to 0.0.0.0/0",
        "Oracle port is not open to entire world": "Oracle port is not open to 0.0.0.0/0",
        "PostgreSQL port is not open to entire world": "PostgreSQL port is not open to 0.0.0.0/0",
        "RDP port is not open to entire world": "RDP port is not open to 0.0.0.0/0",
        "RDP Port is open to entire world": "RDP port is open to 0.0.0.0/0",
        "Exposes only specific ports": "Only specific ports should exposed",
        "Exposes wide port range": "Exposes wide port range",
        "SSH Port is open to entire world": "SSH Port is open to 0.0.0.0/0",
        "SSH port is not open to entire world": "SSH Port is not open to 0.0.0.0/0",
        "Request Logging is not enabled": "Request Logging isn't enabled",
        "Metrics is not enabled.": "Metrics isn't enabled",
        "XRay Tracing is enabled": "AWS X-Ray Distributed Tracing System is enabled",
        "XRay Tracing is not enabled": "AWS X-Ray Distributed Tracing System is not enabled",
        "5XX errors alarms are not enabled.": "5XX errors alarms aren't enabled",
        "Access Logs are not enabled.": "Access Logs aren't enabled",
        "Access Logs are enabled.": "Access Logs are enabled",
        "Field level encryption are not enabled.": "Field level encryption aren't enabled",
        "Field level encryption are enabled.": "Field level encryption are enabled",
        "Dashboards are not being used": "Dashboards aren't used",
        "Errors alarm is not enabled": "Errors alarm isn't enabled",
        "Invocations count alarm is not enabled": "Invocations count alarm isn't enabled",
        "Retention is not set": "Retention isn't set",
        "CPUUtilization alarm is enabled": "CPU Utilization alarm are enabled",
        "CPUUtilization alarm is not enabled": "CPU Utilization alarm isn't enabled",
        "Storage alarm is not enabled": "Storage alarm isn't enabled",
        "Queue Size alarm is not enabled": "Queue Size alarm isn't enabled",
        "Not enabled": "Not enabled",
        "Backup already enabled": "Backup are already enabled",
        "PointInTimeRecovery already enabled": "Point-in-time recovery (PITR) is already enabled",
        "Dead Letter Queue is not configured": "Dead Letter Queue isn't configured",
        "Default timeout is not used": "Default timeout isn't used",
        "Set a proper timeout as per your needs": "Set a proper timeout as per your requirements",
        "Aliasing is not used": "Aliasing isn't used",
        "Aliasing is used": "Aliasing is used",
        "Versioning is not used": "Versioning isn't used",
        "Versioning is used": "Versioning is used",
        "Tracing is enabled.": "Tracing is enabled",
        "Tracing for AWS Lambda is not enabled.": "AWS X-Ray Distributed Tracing System for AWS Lambda isn't enabled",
        "Automated backup is enabled": "Automated backups are enabled",
        "Default security groups are not used": "Default security groups aren't used",
        "Default VPC is used": "Default VPC is being used",
        "Deletion Protection not enabled": "Deletion Protection is not enabled",
        "RDS instance is encrypted at rest": "RDS instance is encrypted at rest",
        "RDS instance is not publicly accessible": "RDS instance isn't publicly accessible",
        "Bucket Analytics is already enabled": "Bucket Analytics are already enabled",
        "Bucket Analytics is not enabled": "Bucket Analytics isn't enabled",
        "Bucket Life cycle rules are configured": "Bucket Life cycle rules are properly configured",
        "Bucket Life cycle rules are not configured": "Bucket Life cycle rules are not configured at all",
        "Access logs are not enabled": "Access logs aren't enabled",
        "Deletes are not MFA enabled": "Deletes are not MFA enabled",
        "Topic does not have any subscriptions": "Topic doesn't have any subscriptions",
        "Topic has subscriptions": "Topic have a subscriptions",
        "Cloud trails are enabled": "CloudTrails are enabled",
        "Encryption not enabled": "Encryptions are not enabled",
        "Global service events are included": "Global service events are included",
        "Log validation is enabled for the cloud trail": "Log validation is enabled for cloudTrail",
        "Certificate is valid for more than 3 months": "This Certificate is valid for more than 3 months",
        "Certificate is expired": "This Certificate is expired"}

    return message_values_maps


def message_list():
    message_values = [
        "User doesn't belong to any group",
        "Already Enabled",
        "This has a recommended value",
        "User should contact the admin to reset the expired password",
        "Root user access keys are not active",
        "User account is not MFA enabled",
        "User account is MFA enabled",
        "CPUUtilization alarm is enabled",
        "VPC flow logs are not enabled.",
        "Subnet has route to the world.",
        "Subnet does not have route to the world.",
        "Key pair is not used",
        "MSSQL port is not open to entire world",
        "MSSQL Port is open to entire world",
        "MySQL port is not open to entire world",
        "MySQL Port is open to entire world",
        "Oracle port is not open to entire world",
        "PostgreSQL port is not open to entire world",
        "RDP port is not open to entire world",
        "RDP Port is open to entire world",
        "Exposes only specific ports",
        "Exposes wide port range",
        "SSH Port is open to entire world",
        "SSH port is not open to entire world",
        "Request Logging is not enabled",
        "Metrics is not enabled.",
        "XRay Tracing is enabled",
        "XRay Tracing is not enabled",
        "5XX errors alarms are not enabled.",
        "Access Logs are not enabled.",
        "Access Logs are enabled.",
        "Field level encryption are not enabled.",
        "Field level encryption are enabled.",
        "Dashboards are not being used",
        "Errors alarm is not enabled",
        "Invocations count alarm is not enabled",
        "Retention is not set",
        "CPUUtilization alarm is not enabled",
        "Storage alarm is not enabled",
        "Queue Size alarm is not enabled",
        "PointInTimeRecovery already enabled",
        "Not enabled",
        "Backup already enabled",
        "Dead Letter Queue is not configured",
        "Default timeout is not used",
        "Set a proper timeout as per your needs",
        "Aliasing is not used",
        "Aliasing is used",
        "Versioning is not used",
        "Versioning is used",
        "Tracing is enabled.",
        "Tracing for AWS Lambda is not enabled.",
        "Automated backup is enabled",
        "Default security groups are not used",
        "Default VPC is used",
        "Deletion Protection not enabled",
        "RDS instance is encrypted at rest",
        "RDS instance is not publicly accessible",
        "Bucket Analytics is already enabled",
        "Bucket Analytics is not enabled",
        "Bucket Life cycle rules are configured",
        "Bucket Life cycle rules are not configured",
        "Access logs are not enabled",
        "Deletes are not MFA enabled",
        "Topic does not have any subscriptions",
        "Topic has subscriptions",
        "Cloud trails are enabled",
        "Encryption not enabled",
        "Global service events are included",
        "Log validation is enabled for the cloud trail",
        "Certificate is valid for more than 3 months",
        "Certificate is expired"
]

    return message_values


def key_map():
    key_maps = {'aws.iam': 'IAM', 'aws.vpc': 'VPC', 'aws.ec2': 'EC2', 'aws.apigateway': 'APIGateway', 'aws.cloudfront':
        'CloudFront', 'aws.cloudwatch': 'CloudWatch', 'aws.dynamodb': 'DynamoDB', 'aws.ebs': 'EBS',
               'aws.elasticsearch': 'ElasticSearch', 'aws.elb': 'ELB', 'aws.lambda': 'Lambda', 'aws.rds': 'RDS',
               'aws.s3': 'S3', 'aws.sns': 'SNS', 'aws.sqs': 'SQS', 'aws.trails': 'CloudTrails',
               'aws.redshift': 'RedShift', 'aws.acm': 'ACM'}
    return key_maps


def service_dic():
    service_dics = ['aws.iam', 'aws.vpc', 'aws.ec2', 'aws.apigateway', 'aws.cloudfront', 'aws.cloudwatch',
                   'aws.dynamodb', 'aws.ebs', 'aws.elasticsearch', 'aws.elb', 'aws.lambda', 'aws.rds', 'aws.s3',
                   'aws.sns', 'aws.sqs', 'aws.trails', 'aws.redshift', 'aws.acm']
    return service_dics


def action_list():
    action_lists = [
            "Keep only 3 admins",
            "User groups for granting access to the users",
            "Add an ExternalId",
            "Enable MFA for the user",
            "Enable vpc flow logs for debugging access requests to the VPC.",
            "If the subnet is private then it shouldn't have route to the world.",
            "Delete the key pair",
            "Set this to 8",
            "Set this to 90",
            "Set this to 3",
            "Restrict MySQL port",
            "Restrict MSSQL port",
            "Restrict RDP port",
            "Remove rule containing IP protocol: -1",
            "Restrict SSH port",
            "Enable XRay Tracing for API",
            "Set 5XX errors alarms.",
            "Enable Access Logs.",
            "Enable field level encryption.",
            "Set 5XX errors alarms",
            "Create dashboards for various performance metrics",
            "Set Errors alarm",
            "Set Invocations count alarm",
            "Set proper Retention",
            "Set CPUUtilization alarm",
            "Set Storage alarm",
            "Set Queue Size alarm",
            "Enable table PointInTimeRecovery",
            "Review once in every month",
            "Configure DLQ",
            "Analyze what function is doing and set a proper timeout",
            "Start using Aliasing",
            "Start using versioning",
            "Keep deleting the old versions",
            "The AWS X-Ray integration for AWS Lambda should be enabled.",
            "Update is disabled for this function. Please create new function",
            "All Good",
            "Use custom VPC instead of default VPC",
            "Enable deletion protection for all production instances",
            "Reserve the instance to save costs",
            "Disable open access to any user",
            "Enable Bucket Analytics",
            "Configure life cycle rules",
            "Enable access logs",
            "Enable MFADelete",
            "Either add subscription or delete the topic",
            "Enable encryption at rest",
            "Renew the certificate or remove it if no longer needed"
        ]
    return action_lists


def action_map():
    action_maps = {
        "Keep only 3 admins": "Recommended to keep only 3 admins in one account",
        "User groups for granting access to the users": "Use groups for granting access to the users",
        "Add an ExternalId": "Recommended to add an External-Id",
        "Enable MFA for the user": "Recommended to enable MFA for the user",
        "Enable vpc flow logs for debugging access requests to the VPC.": "Recommended to enable VPC Flow Logs "
                                                                          "for debugging access requests to the VPC",
        "If the subnet is private then it shouldn't have route to the world.": "Recommended that if the subnet is private then it shouldn't have route to the world",
        "Delete the key pair": "Recommended to delete the key pair",
        "Restrict MSSQL port": "Recommended to restrict MSSQL port",
        "Restrict MySQL port": "Recommended to restrict MySQL port",
        "Restrict RDP port": "Recommended to restrict RDP port",
        "Set this to 8": "Recommended length should be least 8 or more",
        "Set this to 90": "Recommended to change the password after 90 days",
        "Set this to 3": "Recommended to change the password",
        "Remove rule containing IP protocol: -1": "Recommended to remove all the rules containing IP protocol: -1",
        "Restrict SSH port": "Recommended to restrict SSH port",
        "Enable XRay Tracing for API": "Recommended to enable AWS X-Ray Tracing for the API",
        "Set 5XX errors alarms.": "Recommended to set 5XX errors alarms",
        "Enable Access Logs.": "Recommended to enable Access Logs ",
        "Enable field level encryption.": "Recommended to enable field level encryption",
        "Set 5XX errors alarms": "Recommended to set 5XX errors alarms",
        "Create dashboards for various performance metrics": "Recommended to create dashboards for various performance metrics ",
        "Set Errors alarm": "Recommended to set Errors alarm",
        "Set Invocations count alarm": "Recommended to set Invocations count alarm",
        "Set proper Retention": "Recommended to set proper Retention",
        "Set CPUUtilization alarm": "Recommended to set CPU Utilization alarm",
        "Set Storage alarm": "Recommended to set Storage alarm",
        "Set Queue Size alarm": "Recommended to set SQS Queue Size alarm",
        "Enable table PointInTimeRecovery": "Recommended to enable table Point-in-time recovery (PITR)",
        "Review once in every month": "Recommended to eeview once in every month",
        "Configure DLQ": "Recommended  to configure SQS dead-letter queue",
        "Analyze what function is doing and set a proper timeout": "Recommended to analyze what the function is doing and set a proper timeout",
        "Start using Aliasing": "Recommended to start using Aliasing",
        "Start using versioning": "Recommended to Start using versioning",
        "Keep deleting the old versions": "Recommended  to keep deleting the old versions",
        "The AWS X-Ray integration for AWS Lambda should be enabled.": "Recommended to enable the AWS X-Ray integration for AWS Lambda",
        "Update is disabled for this function. Please create new function": "Recommended to create a new function, since update is disabled for this function",
        "All Good": "Everything is Good",
        "Use custom VPC instead of default VPC": "Recommended to use custom VPC instead of the default VPC",
        "Enable deletion protection for all production instances": "Recommended to enable deletion protection for all production instances",
        "Reserve the instance to save costs": "Recommended to reserve the instance to save costs",
        "Disable open access to any user": "Recommended to disable open access to any user ",
        "Enable Bucket Analytics": "Recommended to enable Bucket Analytics",
        "Configure life cycle rules": "Recommended to configure life cycle rules",
        "Enable access logs": "Recommended to enable access logs",
        "Enable MFADelete": "Recommended to enable MFA Delete ",
        "Either add subscription or delete the topic": "Recommended to either add subscription or delete the topic",
        "Enable encryption at rest": "Recommended to enable encryption at rest ",
        "Renew the certificate or remove it if no longer needed": "Recommended to renew the certificate or remove it if no longer needed"
    }

    return action_maps